### ISSUE TITLE
Linkage causes deadlocks

### ISSUE THREAD

**Issue by cjhkramer** [UnionSoft/sysstate#16]
Linkage causes deadlocks:
```
javax.persistence.PersistenceException: org.hibernate.exception.LockAcquisitionException: Deadlock found when trying to get lock; try restarting transaction
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1377)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1300)
	at org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1387)
	at org.hibernate.ejb.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:108)
	at nl.unionsoft.sysstate.dao.impl.InstanceLinkDaoImpl.delete(InstanceLinkDaoImpl.java:48)
	at sun.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy59.delete(Unknown Source)
	at nl.unionsoft.sysstate.logic.impl.InstanceLinkLogicImpl.unlink(InstanceLinkLogicImpl.java:29)
	at nl.unionsoft.sysstate.logic.impl.InstanceLinkLogicImpl.link(InstanceLinkLogicImpl.java:42)
	at nl.unionsoft.sysstate.plugins.selfdiagnose.SelfDiagnoseStateResolverImpl.link(SelfDiagnoseStateResolverImpl.java:166)
	at nl.unionsoft.sysstate.plugins.selfdiagnose.SelfDiagnoseStateResolverImpl.handleXmlObject(SelfDiagnoseStateResolverImpl.java:135)
	at nl.unionsoft.sysstate.plugins.http.XMLBeanStateResolverImpl.handleEntity(XMLBeanStateResolverImpl.java:40)
	at nl.unionsoft.sysstate.plugins.http.HttpStateResolverImpl.handleHttpResponse(HttpStateResolverImpl.java:102)
	at nl.unionsoft.sysstate.plugins.http.HttpStateResolverImpl.setState(HttpStateResolverImpl.java:67)
	at nl.unionsoft.sysstate.logic.impl.StateLogicImpl.updateState(StateLogicImpl.java:157)
	at nl.unionsoft.sysstate.logic.impl.StateLogicImpl.requestStateForInstance(StateLogicImpl.java:136)
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy54.requestStateForInstance(Unknown Source)
	at nl.unionsoft.sysstate.job.UpdateInstanceJob.execute(UpdateInstanceJob.java:47)
	at nl.unionsoft.sysstate.job.AutowiringJob.execute(AutowiringJob.java:17)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
Caused by: org.hibernate.exception.LockAcquisitionException: Deadlock found when trying to get lock; try restarting transaction
	at org.hibernate.dialect.MySQLDialect$1.convert(MySQLDialect.java:392)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:110)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:129)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
	at com.sun.proxy.$Proxy56.executeUpdate(Unknown Source)
	at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:95)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:413)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:282)
	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1264)
	at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:116)
	at org.hibernate.ejb.QueryImpl.internalExecuteUpdate(QueryImpl.java:188)
	at org.hibernate.ejb.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:99)
	... 34 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at sun.reflect.GeneratedConstructorAccessor115.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1064)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1990)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2151)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2625)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2119)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2415)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2333)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2318)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractStatementProxyHandler.continueInvocation(AbstractStatementProxyHandler.java:122)
	... 43 more
2015-05-11 07:01:03,956 INFO  [nl.unionsoft.sysstate.logic.impl.StateLogicImpl] State 'State [id=38, description=Status 200, state=STABLE]' for instance 'InstanceDto [id=601, name=STEP-PRO2]' hasn't changed, updating timestamps, rating & messages only...
2015-05-11 07:01:03,976 INFO  [nl.unionsoft.sysstate.plugins.http.HttpStateResolverImpl] Preparing httpRequest...
2015-05-11 07:01:03,975 INFO  [nl.unionsoft.sysstate.plugins.selfdiagnose.SelfDiagnoseStateResolverImpl] The projectEnvironment for project [igs] and environment [pro] could not be found.
2015-05-11 07:01:03,974 INFO  [nl.unionsoft.sysstate.logic.impl.StateLogicImpl] State 'State [id=39, description=80.0.18.77, state=STABLE]' for instance 'InstanceDto [id=1309, name=PMT]' hasn't changed, updating timestamps, rating & messages only...
2015-05-11 07:01:03,973 INFO  [nl.unionsoft.sysstate.logic.impl.StateLogicImpl] State 'State [id=44, description=81.0.6.1835, state=STABLE]' for instance 'InstanceDto [id=602, name=SYS-PRO2]' hasn't changed, updating timestamps, rating & messages only...
2015-05-11 07:01:03,970 INFO  [nl.unionsoft.sysstate.plugins.http.HttpStateResolverImpl] Preparing httpRequest...
2015-05-11 07:01:03,969 WARN  [nl.unionsoft.sysstate.plugins.http.HttpStateResolverImpl] Caught Exception while performing request: org.hibernate.exception.LockAcquisitionException: Deadlock found when trying to get lock; try restarting transaction
```

**Comment by TiSsaa** [comment]
+1
